name: Deploy Node.js Backend to Render

on:
  push:
    paths:
      - 'backend/**'
  pull_request:
    paths:
      - 'backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: BACKEND_ENVIRONMENT
      url: https://my-backend.onrender.com

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Render
        uses: jakejarvis/render-deploy-action@v1
        with:
          apiKey: ${{ secrets.RENDER_API_KEY }}
          serviceId: ${{ secrets.RENDER_SERVICE_ID }}
          branch: ${{ github.ref_name }}
          waitForDeploy: true
          buildArgs: |
            API_URL=${{ secrets.API_URL }}
            GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}
            ELEVENLABS_KEY=${{ secrets.ELEVENLABS_KEY }}
            LIVEKIT_URL=${{ secrets.LIVEKIT_URL }}
            LIVEKIT_API_KEY=${{ secrets.LIVEKIT_API_KEY }}
            LIVEKIT_API_SECRET=${{ secrets.LIVEKIT_API_SECRET }}
