name: Deploy Node.js Backend to Render

on:
  push:
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: BACKEND_ENVIRONMENT
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Render CLI
        run: |
          curl -fsSL https://cdn.rendertool.com/install.sh | bash

      - name: Deploy service
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          ELEVENLABS_KEY: ${{ secrets.ELEVENLABS_KEY }}
          LIVEKIT_URL: ${{ secrets.LIVEKIT_URL }}
          LIVEKIT_API_KEY: ${{ secrets.LIVEKIT_API_KEY }}
          LIVEKIT_API_SECRET: ${{ secrets.LIVEKIT_API_SECRET }}
        run: |
          render service deploy \
            --service-id ${{ secrets.RENDER_SERVICE_ID }} \
            --branch $GITHUB_REF_NAME \
            --build-env GEMINI_API_KEY=$GEMINI_API_KEY \
            --build-env ELEVENLABS_KEY=$ELEVENLABS_KEY \
            --build-env LIVEKIT_URL=$LIVEKIT_URL \
            --build-env LIVEKIT_API_KEY=$LIVEKIT_API_KEY \
            --build-env LIVEKIT_API_SECRET=$LIVEKIT_API_SECRET
